### PR TITLE
fix: add missing variable declaration

### PR DESCRIPTION
**Pull request by brolag**
Fixed this missing declaration

image

### CODE REVIEW

**Comment by adilanchian** [comment]
Thanks so much for this!! Awesome addition!

Can you do one thing for me: it looks like your linter made some changes when you saved. Could you remove those changes and only include your copy addition?

**Review by adilanchian — CHANGES_REQUESTED** [review]
Thanks so much for this!! Awesome addition!

Can you do one thing for me: it looks like your linter made some changes when you saved. Could you remove those changes and only include your copy addition?

**Review by kotp — COMMENTED** [review]
I would not include the changes for the headers.  This issue says "add missing variable declaration" and it should be the only change here.

Otherwise if needing to revert, a lot of other things are reverted along with the wanted change.  (So at least separate commits).

Really, I appreciate the work done.  But it is too much work completed for the stated goal.

**Comment by adilanchian** [comment]
@kotp - much appreciated for the thoughts!

Ya I ended up blocking the PR for now until those changes are reverted :). Good looking out 🤘

**Comment by brolag** [comment]
@adilanchian I reverted the changes, thanks for letting me know!

**Comment by kotp** [comment]
You could re-request review, dismissing the review that requested changes.  It should bring the PR back to the top of the list, as it would be indicated as ready.

**Comment by brolag** [comment]
I'll do that @kotp, thanks for the help :)

**Review by DavidBarrick — APPROVED** [review]

**Review by adilanchian — APPROVED** [review]

**Comment by adilanchian** [comment]
@all-contributors please add @brolag  for doc

**Pull request merged**
