### PR TITLE
Clarifying getting the direct image from imgur

### PR DESCRIPTION
**Pull request by zzJZzz**
There is a rare instance where running ```npx hardhat``` doesn't start the sample project prompt/wizard.
If that happens then you can manually create a hardhat.config.js and a scripts folder with a sample-scripts.js file. 

I wrote out those instructions and sample file contents.

This was discovered when a friend of mine was stuck in the project. This is how I was able to help him solve it and get the greeter running.

### CODE REVIEW

**Comment by adilanchian** [comment]
This is a super cool change! Really curious about this though - 

1. What OS was your friend on?
2. What did you try before going about this method?

@farzaa @DavidBarrick curious if either of you have ran into this?

**Comment by zzJZzz** [comment]
He was on a Mac. He's brand new to coding. I'm a junior dev that's brand
new to Blockchain.

I had him delete the directory and start over.

Googled the error code.

Double checked the dependencies.

Looked back over the steps in the tutorial.
Realized it wasn't asking for the prompt.

Thought maybe hardhat was installed globally but it didn't appear to be.

'ls' the directory and compared to mine and realized the script error was
because there was no config file. Tried to find a way to manually with
hardhat --config.

When that didn't work. I copied my file and have him 'touch' a file, paste,
and save with the config and the sample-script.

Hopefully that makes sense. It was 1am and I'm still recovering from the
sleep!

Thanks,
JZ

**Comment by zzJZzz** [comment]
MacBook Pro  macOS Big Sur

**Comment by zzJZzz** [comment]
I also forgot to say Thank you!

**Comment by adilanchian** [comment]
Thanks for the thoughts here! 

Im trying to if there may be a better way to approach this right now @farzaa what do you think here?

**Comment by zzJZzz** [comment]
No doubt. I'm sure there are!

I was just glad to figure it out.

**Review by zzJZzz — COMMENTED** [review]
I didn't realize my new PR would get lumped in to my previous PR.

Is it possible to just look at this part?

NFT_Collection/Section_2/Lesson_4_Create_A_Contract_That_Mints_NFTs.md

Thank you,
JZ

**Comment by zzJZzz** [comment]
Ahhhh. I wanted to make this change only
NFT_Collection/Section_2/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
I added one line.

I tried to delete my other change, based off of your comments. Thank you!

I think I made things worst. My apologies. I am excited to contribute to a project.

**Comment by adilanchian** [comment]
Haha oh no!

You actually removed an entire file :P. 

Since your change was small, it might make more sense to just delete this branch and start fresh. There were also things that changed! 

DM me in Discord if you need some help here :)

**Comment by zzJZzz** [comment]
Thank you. That's what I'll do! Of anyone submits the change before me just
sent them hahaha

**Comment by adilanchian** [comment]
@zzJZzz No worries!! I created an issue for #102 

This is your change so I'm going to close out this PR and will wait for you to submit a new PR with this change :). 

You got this! Let me know if you have any questions and I can help you out! There is also some instructions in this repo's README on how to easily submit changes (I made a little video hehe)

**Comment by zzJZzz** [comment]
Nevermind. I saw you merged! Thank you!

**Pull request closed without merging**
