### PR TITLE
Typo fix - All mention of currency now Ether

### PR DESCRIPTION
**Pull request by offgridauthor**
Went through solidity lessons and changed any mention of 'ethereum' referring to currency; should be 'ether' or ETH.

### CODE REVIEW

**Review by adilanchian — CHANGES_REQUESTED** [review]
I think a better change for this would be `ETH` instead of `Ether` whenever we are talking about currency!

Thoughts?

**Comment by farzaa** [comment]
PR creator is right, ether is correct.

**Comment by adilanchian** [comment]
@farzaa I'm a fan of `ETH` instead of `Ether` in this context - thoughts?

@offgridauthor - Looks like we got some conflicts here ! Let me know if you want me to fix or you can :). Just lemme know!

**Comment by adilanchian** [comment]
@offgridauthor - just checking in! Let me know if you are able to get this in, if not I can make the quick change :)

Thanks!

**Comment by offgridauthor** [comment]
@adilanchian - sorry I missed seeing this. Should be resolved now.

**Comment by adilanchian** [comment]
Thanks @offgridauthor !

We actually want to standardize `ETH` here instead of `Ether`. While both are right, we prefer to go with `ETH`. 

Would you mind making this change for me? Sorry about you having to keep going back haha

Lemme know!

**Comment by offgridauthor** [comment]
Submitting new PR  #100

**Pull request closed without merging**
